services:
  - type: web
    name: moto-bot
    env: python
    region: frankfurt
    buildCommand: "pip install pyTelegramBotAPI flask"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "6543210987:AAFx123abc456DEF789ghi_JKLMnopQRST"
      - key: MANAGERS
        value: "925955872,293668596"
